language: node_js
node_js:
  - node
script:
  - jspm config registries.github.auth ${GH_TOKEN}
  - jspm install
  - gulp
  - npm run deploy
env:
  global:
  - GH_REF=github.com/bastijns-jeroen/dashboard.git
  - secure: qRdCh1VKtZvP3oq7ii0rIeN3yrmGr6UioghNeEZaXH9vbvx6EGfzs3ZEMH7uFSAmdqnDD+L37spm8ABim6yzExz2z5MATWw4VCN6phtL3riEGkJc/jG+fi8kZiWIKKQtYXPVy/4SfappBhzi9CFmgMccicKVN5PeuoSgEXxgaKmjtDZRaeCF/z40pfyAA9nmzTU7pt0wTzPaYz9bEFSt/3+jwbsEV0fi0FsFUMmKRsMDN4GHfjVMDU5UkvseHD4UGGPjtlDUbjZp+CTlGv2QK2rDhF8RcWlStaHcbHzzpIUJCnx5Xl/IXoPLc4QYRGIPCrmlIZKV8MeDmjp6eE4YyRdJ/oGvVEv6keHTSubAU0ZvdQ+8wgmb5+5TUc4j8B1GTPLU4LT6DrzyNWDqqZpbFKCR4wmg7HBmYHvgDstp8vpKaAe0DjWmEyaLbF0p9+DtzJRb6rTX5P5LgzkOeIHU531fpYgbrWrQbJwL+rkCAqMcRNPpPSbsKN48G3Ons3P1ljxnDYT0LNYKS75Jv/66MiTjb4amhG2jdE/O9W6dqioG+4Rsim2Z7HBE6oRQbSR96R9VCn8Juoki+fhY6aIX3Lm/Ep6+EVlI5rNlSRiQ0lpj/M31At5vr6ek9o0Jz9XFY1bTL0wzHkFNcFk7rzY4SKD03YVYwoYZnEyF4RfAMn0=
